# Generated by Django 5.1.4 on 2024-12-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mastering", "0002_vocalmastering_delete_vocalprocessingjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocalmastering",
            name="reference_audio",
            field=models.FileField(blank=True, null=True, upload_to="references/"),
        ),
    ]
