# Generated by Django 5.1.4 on 2024-12-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mastering", "0003_vocalmastering_reference_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vocalmastering",
            name="reference_audio",
        ),
    ]
